### ISSUE TITLE
mpvue中，使用npm install await不起作用

### ISSUE THREAD

**Issue by kala888** [youngjuning/wxPromise#10]
搞错了。。。报错bug了

**Comment by kala888** [comment]
搞错了。。。报错bug了

**Comment by youngjuning** [comment]
你在 mpvue 中使用这个了？我现在刚做完小程序原生的这部分。不知道 wepy 和 mpvue 中使用会遇到什么情况。你可以说一下吗？

**Comment by kala888** [comment]
@youngjuning wepy1.x 图灵不完备，组件化应用是个巨坑，简单应用还凑合，mpvue好的多，还在研究，没有大规模编码尝试。

**Comment by youngjuning** [comment]
async 那个需要单独引入一次，你应该已经看到了。谢谢你的反馈
