### ISSUE TITLE
能否提供参考的样例

### ISSUE THREAD

**Issue by xswby** [youngjuning/wxPromise#13]

**Comment by youngjuning** [comment]
你看我写的文档就可以了，你如果是对微信的 api，不熟悉，那应该左转官方文档。

如下面，所有微信的异步 api 都可以按照这个形式使用：

![image](https://user-images.githubusercontent.com/13204332/40337537-c1c39afa-5da2-11e8-8f9e-749c358c2182.png)

**Comment by youngjuning** [comment]
本人微信号 y_m_j_x
