### ISSUE TITLE
asycn方法的finally会报错

### ISSUE THREAD

**Issue by climbingDog** [youngjuning/wxPromise#15]
this.syncLocation(this).then(res=>{
      console.log('<-------->'+res);
    })
    .catch(err=>{
      console.log(err);
    })
//这里加上去会报错。
    .finally(() => {
      wx.hideLoading()
    })

//这里是方法定义
syncLocation: async (ops) => {
let that = ops;
    // let loc = new Location();
    try{
    let data = await Location.getCurrentLocation();

    console.log("========72=====" + Location.jd);
    that.setData({ location: data });
    return data;
    } catch (e) {
      throw e
    };

**Comment by youngjuning** [comment]
https://m.runoob.com/jsref/jsref-try-catch.html

**Comment by youngjuning** [comment]
封装的微信的API是支持finally。自定义的方法想要支持finally。需要自己处理的。可以参考上面的链接
