### ISSUE TITLE
里面的方法有点偏离了你做promise的初衷啊

### ISSUE THREAD

**Issue by Wolferring** [youngjuning/wxPromise#16]

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/41012476-418f81ae-6974-11e8-8fb0-575a07f24c9a.png)，这些扩展的方法都是经过深思熟虑的，有很多我常用的并没有加进去，主要是考虑到通用性

**Comment by youngjuning** [comment]
最终，我还是移除了扩展的方法。因为每个人都有自己的使用场景，实难维护！
