### ISSUE TITLE
仿照demo使用，提示this.asyncFunc(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by sonicsunsky** [youngjuning/wxPromise#18]
**this.asyncFunc(...).then(...).catch(...).finally is not a function;**at "pages/iview-test/iview-test" page lifeCycleMethod onLoad function
TypeError: this.asyncFunc(...).then(...).catch(...).finally is not a function
    at r.onLoad (http://127.0.0.1:63760/appservice/pages/iview-test/iview-test.js:235:15)
    at r.<anonymous> (http://127.0.0.1:63760/appservice/__dev__/WAService.js:2:4625)
    at q (http://127.0.0.1:63760/appservice/__dev__/WAService.js:1:9110)
    at Z (http://127.0.0.1:63760/appservice/__dev__/WAService.js:1:11143)
    at te (http://127.0.0.1:63760/appservice/__dev__/WAService.js:1:11413)
    at Function.<anonymous> (http://127.0.0.1:63760/appservice/__dev__/WAService.js:1:14157)
    at http://127.0.0.1:63760/appservice/__dev__/WAService.js:1:19990
    at http://127.0.0.1:63760/appservice/__dev__/WAService.js:8:19668
    at Array.forEach (<anonymous>)
    at Function.<anonymous> (http://127.0.0.1:63760/appservice/__dev__/WAService.js:8:19648)
console.error @ VM23502:1
errorReport @ WAService.js:5
thirdErrorReport @ WAService.js:5
(anonymous) @ WAService.js:5
(anonymous) @ WAService.js:2
q @ WAService.js:1
Z @ WAService.js:1
te @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:8
(anonymous) @ WAService.js:8
(anonymous) @ WAService.js:6
a @ appservice?t=1529636407442:7941
d.registerCallback @ appservice?t=1529636407442:7941
m.forEach @ appservice?t=1529636407442:7941
d @ appservice?t=1529636407442:7941
j.onmessage @ appservice?t=1529636407442:7941

```
import regeneratorRuntime from '../../utils/wxPromise.js'
import '../../utils/wxPromise.js'

asyncFunc: async function (username) {
    try {
      let result;
      await this.awaitFunc().then(res => {
        console.log(res);
        result = res;
      })
      return result;
    } catch (e) {
      throw e
    }
  },
  awaitFunc() {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve([1, 2, 3])
      }, 500)
    })
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {
    this.asyncFunc('youngjuning').then((res) => {
        console.log(res)
      })
      .catch((err) => {
        console.log(err)
      })
    .finally(() => {
      // wx.hideLoading()
      console.log("finally");
    })
  },

```

**Comment by youngjuning** [comment]
demo里边的那个异步函数是封装了支持 finally 的（所有的wx API 都支持 finally），但是你自定义的方法是不支持的。你可以试试：

```js
asyncFunc: async function (username) {
    try {
      let result;
      await this.awaitFunc().then(res => {
        console.log(res);
        result = res;
      })
      return result;
    } catch (e) {
      throw e
    } finally() {
      ......
    }
  },
```

或者不使用 finally，把 `.finally` 删掉。
