### ISSUE TITLE
请问为什么安转是这个命令 npm i wx-promise-pro -D

### ISSUE THREAD

**Issue by bravekingzhang** [youngjuning/wxPromise#20]
貌似安装之后加入到了 devDependencies 这个下面，难道生产环境不需要么？

**Comment by youngjuning** [comment]
嗯嗯，你把 -D 去掉的，你是用 mpvue 开发的？

**Comment by kala888** [comment]
@bravekingzhang 对mpvue支持有点小问题，我提了个pull request，我本地可以运行了
#23

**Comment by youngjuning** [comment]
@bravekingzhang @kala888 最近忙于 react native 的学习与工作，感谢支持，已merge
